import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X, IndianRupee, TrendingUp, Building2, ShieldCheck,
  Briefcase, Zap, Heart, Download, Calendar, ChevronRight
} from 'lucide-react';
import {
  PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend
} from 'recharts';

const fmt = (n) => Number(n || 0).toLocaleString('en-IN');

const COLORS = {
  basic:             '#6366f1',
  hra:               '#8b5cf6',
  specialAllowance:  '#a78bfa',
  performanceBonus:  '#f59e0b',
  lta:               '#10b981',
  medicalAllowance:  '#06b6d4',
  telephoneAllowance:'#3b82f6',
  conveyanceAllowance: '#ec4899',
  epfEmployer:       '#ef4444',
  esicEmployer:      '#f97316',
  gratuity:          '#84cc16',
  healthInsurance:   '#14b8a6',
  lifeInsurance:     '#0ea5e9',
  professionalTax:   '#64748b',
};

const EARNING_LABELS = {
  basicSalary:        'Basic Salary',
  hra:                'House Rent Allowance (HRA)',
  specialAllowance:   'Special Allowance',
  performanceBonus:   'Performance Bonus',
  lta:                'Leave Travel Allowance (LTA)',
  medicalAllowance:   'Medical Allowance',
  telephoneAllowance: 'Telephone Allowance',
  conveyanceAllowance:'Conveyance Allowance',
};

const CONTRIB_LABELS = {
  epfEmployer:    "EPF – Employer's Contribution (12%)",
  esicEmployer:   "ESIC – Employer's Contribution (3.25%)",
  gratuity:       'Gratuity (4.81% of Basic)',
  healthInsurance:'Group Health Insurance',
  lifeInsurance:  'Group Life Insurance',
  professionalTax:'Professional Tax (Annual)',
};

const CustomTooltip = ({ active, payload }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-slate-900/95 border border-slate-700 px-4 py-3 rounded-2xl shadow-2xl backdrop-blur-sm">
      <p className="text-[9px] font-black uppercase tracking-widest text-slate-400 mb-1">
        {payload[0].name}
      </p>
      <p className="text-sm font-black text-white">₹{fmt(payload[0].value)}</p>
    </div>
  );
};

/**
 * CTCBreakdown
 * @param {object}   ctc      – CTC document from the DB (with components, employerContributions, totals)
 * @param {string}   name     – Employee name
 * @param {function} onClose  – Close handler
 */
const CTCBreakdown = ({ ctc, name, onClose }) => {
  if (!ctc) return null;

  const { components = {}, employerContributions = {}, totals = {} } = ctc;

  // Pie data — merge both sets
  const earningSlices = Object.entries(components)
    .filter(([, v]) => Number(v) > 0)
    .map(([k, v]) => ({ name: EARNING_LABELS[k] || k, value: Number(v), color: COLORS[k] || '#6366f1', group: 'Earnings' }));

  const contribSlices = Object.entries(employerContributions)
    .filter(([, v]) => Number(v) > 0)
    .map(([k, v]) => ({ name: CONTRIB_LABELS[k] || k, value: Number(v), color: COLORS[k] || '#ef4444', group: 'Employer' }));

  const pieData = [...earningSlices, ...contribSlices];

  const handleDownload = () => {
    // Generate a clean text summary the employee can save
    const lines = [
      'CTC BREAKUP STATEMENT — NEXOVTECH',
      '─'.repeat(50),
      `Employee  : ${name}`,
      `Effective : ${ctc.effectiveDate || 'N/A'}`,
      `Currency  : ${ctc.currency || 'INR'}`,
      '',
      '── EARNINGS (Annual) ──',
      ...Object.entries(components).map(([k, v]) => `  ${(EARNING_LABELS[k] || k).padEnd(38)} ₹${fmt(v)}`),
      '',
      `  ${'Total Earnings'.padEnd(38)} ₹${fmt(totals.totalAnnualEarnings)}`,
      '',
      "── EMPLOYER'S CONTRIBUTIONS (Annual) ──",
      ...Object.entries(employerContributions).map(([k, v]) => `  ${(CONTRIB_LABELS[k] || k).padEnd(38)} ₹${fmt(v)}`),
      '',
      `  ${'Total Employer Contributions'.padEnd(38)} ₹${fmt(totals.totalAnnualEmployerContrib)}`,
      '─'.repeat(50),
      `  ${'ANNUAL CTC'.padEnd(38)} ₹${fmt(totals.annualCTC)}`,
      `  ${'MONTHLY CTC'.padEnd(38)} ₹${fmt(totals.monthlyCTC)}`,
      `  ${'EST. MONTHLY IN-HAND'.padEnd(38)} ₹${fmt(totals.monthlyInHand)}`,
      '─'.repeat(50),
      '',
      'Note: In-hand estimate excludes income tax (TDS) which varies per tax regime.',
      'This document is auto-generated by NexovTech Administration.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CTC_Breakdown_${(name || 'Employee').replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[200] flex items-start justify-center p-4 sm:p-6 overflow-y-auto">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-slate-900/60 backdrop-blur-xl"
        />

        {/* Panel */}
        <motion.div
          initial={{ opacity: 0, scale: 0.96, y: 24 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.96, y: 24 }}
          transition={{ type: 'spring', stiffness: 300, damping: 28 }}
          className="relative w-full max-w-3xl z-10 my-8"
        >
          {/* ── Hero Banner ── */}
          <div className="bg-slate-900 rounded-[32px] p-8 sm:p-10 text-white relative overflow-hidden mb-4">
            {/* Glow orbs */}
            <div className="absolute -top-16 -left-16 w-64 h-64 bg-indigo-500/20 rounded-full blur-[80px] pointer-events-none" />
            <div className="absolute -bottom-16 -right-16 w-64 h-64 bg-violet-500/10 rounded-full blur-[80px] pointer-events-none" />

            <div className="relative z-10 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6">
              <div>
                <p className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-400 mb-2">
                  Cost to Company — Annual Breakdown
                </p>
                <h1 className="text-3xl sm:text-4xl font-black tracking-tighter leading-none mb-1">
                  {name}
                </h1>
                {ctc.effectiveDate && (
                  <p className="text-slate-400 text-[11px] font-bold flex items-center gap-1.5 mt-2">
                    <Calendar size={11} /> Effective: {ctc.effectiveDate}
                  </p>
                )}
              </div>
              <button
                onClick={onClose}
                className="absolute top-4 right-4 sm:static p-2 rounded-xl bg-white/5 hover:bg-white/10 transition-all text-slate-400 hover:text-white shrink-0"
              >
                <X size={20} />
              </button>
            </div>

            {/* Three headline numbers */}
            <div className="relative z-10 grid grid-cols-3 gap-3 sm:gap-6 mt-8">
              {[
                { label: 'Annual CTC', value: `₹${fmt(totals.annualCTC)}`, accent: 'text-indigo-400' },
                { label: 'Monthly CTC', value: `₹${fmt(totals.monthlyCTC)}`, accent: 'text-violet-400' },
                { label: 'Monthly In-Hand*', value: `₹${fmt(totals.monthlyInHand)}`, accent: 'text-emerald-400' },
              ].map(({ label, value, accent }) => (
                <div key={label} className="flex flex-col p-3 sm:p-5 rounded-2xl bg-white/[0.04] border border-white/[0.06]">
                  <span className="text-[8px] sm:text-[9px] font-black uppercase tracking-widest text-slate-400 mb-1.5">{label}</span>
                  <span className={`text-sm sm:text-xl font-black tracking-tighter ${accent}`}>{value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* ── Body ── */}
          <div className="bg-white rounded-[32px] border border-slate-100 shadow-2xl overflow-hidden">
            {/* Pie Chart */}
            <div className="p-6 sm:p-10 border-b border-slate-50">
              <h3 className="text-[13px] font-black text-slate-900 uppercase tracking-widest mb-6 flex items-center gap-2">
                <TrendingUp size={16} className="text-indigo-500" /> CTC Composition
              </h3>
              <div className="flex flex-col lg:flex-row items-center gap-6">
                <div className="w-full lg:w-64 h-56 shrink-0">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={pieData}
                        cx="50%"
                        cy="50%"
                        innerRadius={60}
                        outerRadius={95}
                        paddingAngle={2}
                        dataKey="value"
                        strokeWidth={0}
                      >
                        {pieData.map((entry, i) => (
                          <Cell key={i} fill={entry.color} />
                        ))}
                      </Pie>
                      <Tooltip content={<CustomTooltip />} />
                    </PieChart>
                  </ResponsiveContainer>
                </div>

                {/* Summary columns */}
                <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-3 w-full">
                  <div className="flex items-center justify-between p-4 rounded-2xl bg-indigo-50 border border-indigo-100">
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black uppercase tracking-widest text-indigo-400 mb-1">Total Earnings</span>
                      <span className="text-lg font-black text-slate-900">₹{fmt(totals.totalAnnualEarnings)}</span>
                      <span className="text-[9px] text-slate-400 font-bold mt-0.5">per annum</span>
                    </div>
                    <Briefcase size={28} className="text-indigo-200 shrink-0" />
                  </div>
                  <div className="flex items-center justify-between p-4 rounded-2xl bg-rose-50 border border-rose-100">
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black uppercase tracking-widest text-rose-400 mb-1">Employer Contributions</span>
                      <span className="text-lg font-black text-slate-900">₹{fmt(totals.totalAnnualEmployerContrib)}</span>
                      <span className="text-[9px] text-slate-400 font-bold mt-0.5">per annum</span>
                    </div>
                    <Building2 size={28} className="text-rose-200 shrink-0" />
                  </div>
                  <div className="flex items-center justify-between p-4 rounded-2xl bg-emerald-50 border border-emerald-100 sm:col-span-2">
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black uppercase tracking-widest text-emerald-400 mb-1">EPF (Employee Share)</span>
                      <span className="text-base font-black text-slate-900">₹{fmt(totals.epfEmployee)}/mo deducted from gross</span>
                    </div>
                    <ShieldCheck size={24} className="text-emerald-200 shrink-0" />
                  </div>
                </div>
              </div>
            </div>

            {/* Earnings Table */}
            <div className="p-6 sm:p-10 border-b border-slate-50">
              <h3 className="text-[13px] font-black text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2">
                <Briefcase size={14} className="text-indigo-500" /> Earnings Breakdown
              </h3>
              <div className="space-y-2">
                {Object.entries(components).map(([key, val]) => {
                  if (!Number(val)) return null;
                  const pct = totals.annualCTC > 0 ? ((Number(val) / totals.annualCTC) * 100).toFixed(1) : 0;
                  return (
                    <div key={key} className="flex items-center justify-between py-3 px-4 rounded-xl hover:bg-slate-50 transition-colors group">
                      <div className="flex items-center gap-3">
                        <div className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: COLORS[key] || '#6366f1' }} />
                        <span className="text-[12px] font-bold text-slate-700">{EARNING_LABELS[key] || key}</span>
                      </div>
                      <div className="flex items-center gap-4">
                        <span className="text-[10px] text-slate-400 font-bold w-12 text-right hidden sm:block">{pct}%</span>
                        <div className="text-right">
                          <span className="text-[13px] font-black text-slate-900">₹{fmt(val)}</span>
                          <span className="text-[9px] text-slate-400 font-bold ml-1">/yr</span>
                        </div>
                        <span className="text-[11px] font-bold text-slate-400 w-20 text-right hidden sm:block">
                          ₹{fmt(Math.round(Number(val) / 12))}/mo
                        </span>
                      </div>
                    </div>
                  );
                })}
                <div className="flex items-center justify-between py-3 px-4 rounded-xl bg-indigo-600 text-white">
                  <span className="text-[12px] font-black uppercase tracking-widest">Total Earnings</span>
                  <div className="flex items-center gap-4">
                    <span className="text-base font-black">₹{fmt(totals.totalAnnualEarnings)}</span>
                    <span className="text-[11px] font-bold opacity-60 hidden sm:block">
                      ₹{fmt(Math.round(totals.totalAnnualEarnings / 12))}/mo
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Employer Contributions Table */}
            <div className="p-6 sm:p-10 border-b border-slate-50">
              <h3 className="text-[13px] font-black text-slate-900 uppercase tracking-widest mb-4 flex items-center gap-2">
                <Building2 size={14} className="text-rose-500" /> Employer's Statutory Contributions
              </h3>
              <div className="space-y-2">
                {Object.entries(employerContributions).map(([key, val]) => {
                  if (!Number(val)) return null;
                  return (
                    <div key={key} className="flex items-center justify-between py-3 px-4 rounded-xl hover:bg-slate-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: COLORS[key] || '#ef4444' }} />
                        <span className="text-[12px] font-bold text-slate-700">{CONTRIB_LABELS[key] || key}</span>
                      </div>
                      <div className="text-right">
                        <span className="text-[13px] font-black text-slate-900">₹{fmt(val)}</span>
                        <span className="text-[9px] text-slate-400 font-bold ml-1">/yr</span>
                      </div>
                    </div>
                  );
                })}
                <div className="flex items-center justify-between py-3 px-4 rounded-xl bg-rose-500 text-white">
                  <span className="text-[12px] font-black uppercase tracking-widest">Total Contributions</span>
                  <span className="text-base font-black">₹{fmt(totals.totalAnnualEmployerContrib)}</span>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="p-6 sm:p-8 bg-slate-50/50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <p className="text-[9px] text-slate-400 font-bold leading-relaxed max-w-sm">
                * Monthly in-hand is an estimate. Actual take-home may vary based on income tax (TDS), investment declarations, and other deductions as per the applicable tax regime.
              </p>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2.5 px-6 py-3 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-indigo-600 transition-all shadow-lg shrink-0"
              >
                <Download size={14} /> Download CTC Letter
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default CTCBreakdown;
